server:
  shutdown: graceful


spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update


  output:
    ansi:
      enabled: always

  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://music.cxrxabuqxnkd.ap-northeast-2.rds.amazonaws.com:3306/music?serverTimezone=UTC&characterEncoding=UTF-8
      username: hun9003
      password: wlsgns12

  flyway:
    user: hun9003
    password: wlsgns12
    schemas: music
    url: jdbc:mysql://music.cxrxabuqxnkd.ap-northeast-2.rds.amazonaws.com:3306/music?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true
    baseline-on-migrate: true
  mvc:
#    static-path-pattern: /static/**
    view:
      suffix: .html
      prefix: classpath:/static/

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  config: classpath:logback-local.xml
#  level:
#    org.springframework.web.client: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: trace
